/** Generated manifest for the user-supplied built-in companion meme packs. */
interface BuiltInMeme {
  readonly id: string
  readonly scope: string
  readonly title: string
  readonly content: string
  readonly asset: string
  readonly mimeType: string
  readonly description?: string
  readonly tags?: readonly string[]
  readonly transcript?: string
  readonly bytes?: number
  readonly durationMs?: number
}

/**
 * Built in memes.
 * @returns The resulting value.
 */
export const BUILT_IN_MEMES: readonly BuiltInMeme[] = [
  { id: 'builtin-yachiyo-runami-001', scope: 'yachiyo-runami', title: '吃薯片', content: '八千代-吃薯片', asset: '/worldline-experience/companion-memes/yachiyo-runami/001.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-002', scope: 'yachiyo-runami', title: '大咩哟', content: '八千代-大咩哟', asset: '/worldline-experience/companion-memes/yachiyo-runami/002.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-003', scope: 'yachiyo-runami', title: '干嘛', content: '八千代-干嘛', asset: '/worldline-experience/companion-memes/yachiyo-runami/003.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-004', scope: 'yachiyo-runami', title: '喝奶茶', content: '八千代-喝奶茶', asset: '/worldline-experience/companion-memes/yachiyo-runami/004.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-005', scope: 'yachiyo-runami', title: '浇水', content: '八千代-浇水', asset: '/worldline-experience/companion-memes/yachiyo-runami/005.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-006', scope: 'yachiyo-runami', title: '肯定', content: '八千代-肯定', asset: '/worldline-experience/companion-memes/yachiyo-runami/006.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-007', scope: 'yachiyo-runami', title: '你真棒', content: '八千代-你真棒', asset: '/worldline-experience/companion-memes/yachiyo-runami/007.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-008', scope: 'yachiyo-runami', title: '捏脸哭哭', content: '八千代-捏脸哭哭', asset: '/worldline-experience/companion-memes/yachiyo-runami/008.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-009', scope: 'yachiyo-runami', title: '捧脸', content: '八千代-捧脸', asset: '/worldline-experience/companion-memes/yachiyo-runami/009.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-010', scope: 'yachiyo-runami', title: '偷看', content: '八千代-偷看', asset: '/worldline-experience/companion-memes/yachiyo-runami/010.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-011', scope: 'yachiyo-runami', title: '偷笑', content: '八千代-偷笑', asset: '/worldline-experience/companion-memes/yachiyo-runami/011.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-012', scope: 'yachiyo-runami', title: '我吗？', content: '八千代-我吗？', asset: '/worldline-experience/companion-memes/yachiyo-runami/012.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-013', scope: 'yachiyo-runami', title: '无语', content: '八千代-无语', asset: '/worldline-experience/companion-memes/yachiyo-runami/013.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-014', scope: 'yachiyo-runami', title: '嫌弃', content: '八千代-嫌弃', asset: '/worldline-experience/companion-memes/yachiyo-runami/014.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-015', scope: 'yachiyo-runami', title: '陷入了思考', content: '八千代-陷入了思考', asset: '/worldline-experience/companion-memes/yachiyo-runami/015.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-016', scope: 'yachiyo-runami', title: '想要', content: '八千代-想要', asset: '/worldline-experience/companion-memes/yachiyo-runami/016.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-017', scope: 'yachiyo-runami', title: '眼冒爱心', content: '八千代-眼冒爱心', asset: '/worldline-experience/companion-memes/yachiyo-runami/017.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-001', scope: 'iroha-sakayori', title: '给我康康', content: '彩叶-给我康康', asset: '/worldline-experience/companion-memes/iroha-sakayori/001.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-002', scope: 'iroha-sakayori', title: '恐吓', content: '彩叶-恐吓', asset: '/worldline-experience/companion-memes/iroha-sakayori/002.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-003', scope: 'iroha-sakayori', title: '哭哭', content: '彩叶-哭哭', asset: '/worldline-experience/companion-memes/iroha-sakayori/003.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-004', scope: 'iroha-sakayori', title: '墨镜下的泪眼汪汪', content: '彩叶-墨镜下的泪眼汪汪', asset: '/worldline-experience/companion-memes/iroha-sakayori/004.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-005', scope: 'iroha-sakayori', title: '你在叫我吗', content: '彩叶-你在叫我吗', asset: '/worldline-experience/companion-memes/iroha-sakayori/005.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-006', scope: 'iroha-sakayori', title: '睡觉', content: '彩叶-睡觉', asset: '/worldline-experience/companion-memes/iroha-sakayori/006.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-007', scope: 'iroha-sakayori', title: '投降', content: '彩叶-投降', asset: '/worldline-experience/companion-memes/iroha-sakayori/007.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-008', scope: 'iroha-sakayori', title: '问号', content: '彩叶-问号', asset: '/worldline-experience/companion-memes/iroha-sakayori/008.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-001', scope: 'kaguya', title: '唱歌', content: '辉夜-唱歌', asset: '/worldline-experience/companion-memes/kaguya/001.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-002', scope: 'kaguya', title: '对不起', content: '辉夜-对不起', asset: '/worldline-experience/companion-memes/kaguya/002.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-003', scope: 'kaguya', title: '给你一拳', content: '辉夜-给你一拳', asset: '/worldline-experience/companion-memes/kaguya/003.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-004', scope: 'kaguya', title: '好喜欢', content: '辉夜-好喜欢', asset: '/worldline-experience/companion-memes/kaguya/004.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-005', scope: 'kaguya', title: '喝茶', content: '辉夜-喝茶', asset: '/worldline-experience/companion-memes/kaguya/005.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-006', scope: 'kaguya', title: '骄傲', content: '辉夜-骄傲', asset: '/worldline-experience/companion-memes/kaguya/006.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-007', scope: 'kaguya', title: '焦急', content: '辉夜-焦急', asset: '/worldline-experience/companion-memes/kaguya/007.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-008', scope: 'kaguya', title: '惊到了', content: '辉夜-惊到了', asset: '/worldline-experience/companion-memes/kaguya/008.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-009', scope: 'kaguya', title: '就是你', content: '辉夜-就是你', asset: '/worldline-experience/companion-memes/kaguya/009.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-010', scope: 'kaguya', title: '哭哭', content: '辉夜-哭哭', asset: '/worldline-experience/companion-memes/kaguya/010.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-011', scope: 'kaguya', title: '撩头发', content: '辉夜-撩头发', asset: '/worldline-experience/companion-memes/kaguya/011.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-012', scope: 'kaguya', title: '卖萌', content: '辉夜-卖萌', asset: '/worldline-experience/companion-memes/kaguya/012.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-013', scope: 'kaguya', title: '喵', content: '辉夜-喵', asset: '/worldline-experience/companion-memes/kaguya/013.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-014', scope: 'kaguya', title: '你真棒', content: '辉夜-你真棒', asset: '/worldline-experience/companion-memes/kaguya/014.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-015', scope: 'kaguya', title: '什么？', content: '辉夜-什么？', asset: '/worldline-experience/companion-memes/kaguya/015.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-016', scope: 'kaguya', title: '太感人了', content: '辉夜-太感人了', asset: '/worldline-experience/companion-memes/kaguya/016.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-017', scope: 'kaguya', title: '唐笑', content: '辉夜-唐笑', asset: '/worldline-experience/companion-memes/kaguya/017.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-018', scope: 'kaguya', title: '偷看', content: '辉夜-偷看', asset: '/worldline-experience/companion-memes/kaguya/018.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-019', scope: 'kaguya', title: '无语', content: '辉夜-无语', asset: '/worldline-experience/companion-memes/kaguya/019.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-020', scope: 'kaguya', title: '野兽先辈的呐喊', content: '辉夜-野兽先辈的呐喊', asset: '/worldline-experience/companion-memes/kaguya/020.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-021', scope: 'kaguya', title: '余额不足', content: '辉夜-余额不足', asset: '/worldline-experience/companion-memes/kaguya/021.gif', mimeType: 'image/gif' },
  { id: 'builtin-public-001', scope: 'public', title: '110', content: '110', asset: '/worldline-experience/companion-memes/public/001.jpg', mimeType: 'image/jpeg' },
  { id: 'builtin-yachiyo-runami-018', scope: 'yachiyo-runami', title: '蹦蹦跳跳走过来', content: '八千代-蹦蹦跳跳走过来', asset: '/worldline-experience/companion-memes/yachiyo-runami/018.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-019', scope: 'yachiyo-runami', title: '哭哭', content: '八千代-哭哭', asset: '/worldline-experience/companion-memes/yachiyo-runami/019.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-020', scope: 'yachiyo-runami', title: '泪眼', content: '八千代-泪眼', asset: '/worldline-experience/companion-memes/yachiyo-runami/020.gif', mimeType: 'image/gif' },
  { id: 'builtin-yachiyo-runami-021', scope: 'yachiyo-runami', title: '是我哦', content: '八千代-是我哦', asset: '/worldline-experience/companion-memes/yachiyo-runami/021.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-009', scope: 'iroha-sakayori', title: '不好', content: '彩叶-不好', asset: '/worldline-experience/companion-memes/iroha-sakayori/009.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-010', scope: 'iroha-sakayori', title: '带娃', content: '彩叶-带娃', asset: '/worldline-experience/companion-memes/iroha-sakayori/010.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-011', scope: 'iroha-sakayori', title: '好喜欢', content: '彩叶-好喜欢', asset: '/worldline-experience/companion-memes/iroha-sakayori/011.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-012', scope: 'iroha-sakayori', title: '幻想', content: '彩叶-幻想', asset: '/worldline-experience/companion-memes/iroha-sakayori/012.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-013', scope: 'iroha-sakayori', title: '惊吓', content: '彩叶-惊吓', asset: '/worldline-experience/companion-memes/iroha-sakayori/013.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-014', scope: 'iroha-sakayori', title: '困死了', content: '彩叶-困死了', asset: '/worldline-experience/companion-memes/iroha-sakayori/014.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-015', scope: 'iroha-sakayori', title: '流汗', content: '彩叶-流汗', asset: '/worldline-experience/companion-memes/iroha-sakayori/015.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-016', scope: 'iroha-sakayori', title: '沦陷了', content: '彩叶-沦陷了', asset: '/worldline-experience/companion-memes/iroha-sakayori/016.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-017', scope: 'iroha-sakayori', title: '如坠冰窟', content: '彩叶-如坠冰窟', asset: '/worldline-experience/companion-memes/iroha-sakayori/017.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-018', scope: 'iroha-sakayori', title: '完啦', content: '彩叶-完啦', asset: '/worldline-experience/companion-memes/iroha-sakayori/018.gif', mimeType: 'image/gif' },
  { id: 'builtin-iroha-sakayori-019', scope: 'iroha-sakayori', title: '真不错', content: '彩叶-真不错', asset: '/worldline-experience/companion-memes/iroha-sakayori/019.gif', mimeType: 'image/gif' },
  { id: 'builtin-public-002', scope: 'public', title: '给我看超时空辉夜姬', content: '给我看超时空辉夜姬', asset: '/worldline-experience/companion-memes/public/002.jpg', mimeType: 'image/jpeg' },
  { id: 'builtin-kaguya-022', scope: 'kaguya', title: '摆pose', content: '辉夜-摆pose', asset: '/worldline-experience/companion-memes/kaguya/022.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-023', scope: 'kaguya', title: '崩溃', content: '辉夜-崩溃', asset: '/worldline-experience/companion-memes/kaguya/023.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-024', scope: 'kaguya', title: '不情愿', content: '辉夜-不情愿', asset: '/worldline-experience/companion-memes/kaguya/024.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-025', scope: 'kaguya', title: '不要啊', content: '辉夜-不要啊', asset: '/worldline-experience/companion-memes/kaguya/025.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-026', scope: 'kaguya', title: '吃醋', content: '辉夜-吃醋', asset: '/worldline-experience/companion-memes/kaguya/026.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-027', scope: 'kaguya', title: '打音游', content: '辉夜-打音游', asset: '/worldline-experience/companion-memes/kaguya/027.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-028', scope: 'kaguya', title: '大吃特吃', content: '辉夜-大吃特吃', asset: '/worldline-experience/companion-memes/kaguya/028.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-029', scope: 'kaguya', title: '大哭大闹', content: '辉夜-大哭大闹', asset: '/worldline-experience/companion-memes/kaguya/029.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-030', scope: 'kaguya', title: '恶龙咆哮', content: '辉夜-恶龙咆哮', asset: '/worldline-experience/companion-memes/kaguya/030.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-031', scope: 'kaguya', title: '鬼叫', content: '辉夜-鬼叫', asset: '/worldline-experience/companion-memes/kaguya/031.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-032', scope: 'kaguya', title: '好吃', content: '辉夜-好吃', asset: '/worldline-experience/companion-memes/kaguya/032.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-033', scope: 'kaguya', title: '好好吃', content: '辉夜-好好吃', asset: '/worldline-experience/companion-memes/kaguya/033.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-034', scope: 'kaguya', title: '好气', content: '辉夜-好气', asset: '/worldline-experience/companion-memes/kaguya/034.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-035', scope: 'kaguya', title: '好想要', content: '辉夜-好想要', asset: '/worldline-experience/companion-memes/kaguya/035.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-036', scope: 'kaguya', title: '好耶', content: '辉夜-好耶', asset: '/worldline-experience/companion-memes/kaguya/036.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-037', scope: 'kaguya', title: '激动', content: '辉夜-激动', asset: '/worldline-experience/companion-memes/kaguya/037.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-038', scope: 'kaguya', title: '看好你', content: '辉夜-看好你', asset: '/worldline-experience/companion-memes/kaguya/038.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-039', scope: 'kaguya', title: '看戏', content: '辉夜-看戏', asset: '/worldline-experience/companion-memes/kaguya/039.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-040', scope: 'kaguya', title: '流口水', content: '辉夜-流口水', asset: '/worldline-experience/companion-memes/kaguya/040.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-041', scope: 'kaguya', title: '你怎么不早说', content: '辉夜-你怎么不早说', asset: '/worldline-experience/companion-memes/kaguya/041.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-042', scope: 'kaguya', title: '撒娇', content: '辉夜-撒娇', asset: '/worldline-experience/companion-memes/kaguya/042.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-043', scope: 'kaguya', title: '跳舞', content: '辉夜-跳舞', asset: '/worldline-experience/companion-memes/kaguya/043.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-044', scope: 'kaguya', title: '委屈', content: '辉夜-委屈', asset: '/worldline-experience/companion-memes/kaguya/044.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-045', scope: 'kaguya', title: '我发现了什么', content: '辉夜-我发现了什么', asset: '/worldline-experience/companion-memes/kaguya/045.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-046', scope: 'kaguya', title: '行', content: '辉夜-行', asset: '/worldline-experience/companion-memes/kaguya/046.gif', mimeType: 'image/gif' },
  { id: 'builtin-kaguya-047', scope: 'kaguya', title: '耶', content: '辉夜-耶', asset: '/worldline-experience/companion-memes/kaguya/047.gif', mimeType: 'image/gif' },
  { id: 'builtin-public-003', scope: 'public', title: '小南娘爱你', content: '小南娘爱你', asset: '/worldline-experience/companion-memes/public/003.jpg', mimeType: 'image/jpeg' },
  { id: 'builtin-public-004', scope: 'public', title: '小南娘比心', content: '小南娘比心', asset: '/worldline-experience/companion-memes/public/004.gif', mimeType: 'image/gif' },
  {
    id: 'builtin-public-005',
    scope: 'public',
    title: '孤高曼波',
    content: '赛马娘诗歌剧孤高登山曼波，用于荒诞登场、一本正经整活、庆祝与压轴',
    description: '诗歌剧“曼波”哼唱与《孤高之人》登山意象结合的赛马娘二创。适合荒诞登场、独自前进、一本正经整活、庆祝胜利或压轴收尾。',
    tags: [
      '孤高曼波', '曼波', '赛马娘', '闪耀优俊少女', '诗歌剧', '翻车鱼', '孤高之人',
      '登山', 'La La La', '二创', '鬼畜', '整活', '荒诞', '庆祝', '登场', '压轴',
      '视频', 'mp4',
    ],
    transcript: [
      '语义：用孤高登山的严肃画面承载魔性曼波，形成一本正经又荒诞的反差笑点。',
      '推荐：角色突然高调登场、独自完成难事、把小事说得史诗化、庆祝胜利、聊天压轴或对方主动提到曼波和赛马娘时使用。',
      '避免：对方正在严肃求助、悲伤倾诉、表达不适，或当前任务要求克制和专业时使用；不要把“曼波”泛化成任何事物的代称。',
    ].join('\n'),
    asset: '/worldline-experience/companion-memes/public/005.mp4',
    mimeType: 'video/mp4',
    bytes: 5_629_565,
    durationMs: 23_000,
  },
]
