import type {} from '@deepseek-ai/dsh-client-ui-slots'

/** Identifies the package-owned zh value.
 */
export const zh = {
  nav: '世界线', title: '世界线工作台', subtitle: '把设定编译成可验证、可回放、可游玩的世界。',
  local: '仅保存在本机', chooseRoot: '为故事选择一个家', chooseRootHint: '选择一个本地文件夹保存世界、角色和每一次推演。所有创作文件始终归你所有。',
  chooseDirectory: '选择目录', retry: '重试', loading: '正在读取世界线项目库…', rootError: '无法读取项目库',
  library: '我的世界', search: '搜索世界、角色或标签…', newProject: '创造新世界', rescan: '同步本地创作', rootSettings: '创作目录',
  noProjects: '第一条世界线，正等你落笔', noProjectsHint: '从角色故事、世界百科或可游玩剧本开始，也可以导入已有世界包。',
  create: '创建', cancel: '取消', projectName: '项目名称', description: '描述', template: '模板', tags: '标签',
  open: '打开', copy: '创建副本', copyProjectTitle: '创建项目副本', trash: '移到回收站', trashShort: '回收', trashProjectTitle: '确认移入回收站', trashProjectHint: '项目会完整移入可恢复的回收站，不会立即永久删除。', restore: '恢复', trashBin: '回收站', emptyTrash: '清空回收站', emptyTrashTitle: '确认清空回收站', emptyTrashHint: '回收站中的所有世界项目和文件都将被永久删除，此操作无法撤销或恢复。', trashEmpty: '回收站还是空的', emptyTrashDone: '回收站已清空',
  importProject: '导入', exportProject: '导出', sourcePath: '归档文件', destinationPath: '保存位置', chooseArchive: '选择归档文件', chooseSavePath: '选择保存位置', chooseProjectArchive: '选择世界包', chooseBlueprintArchive: '选择蓝图归档', chooseRunArchive: '选择运行存档', includeRuns: '包含运行记录', importConflict: '项目已存在时', importAsCopy: '创建独立副本', replaceRecoverably: '替换并保留到回收站', cancelOnConflict: '取消导入',
  importBlueprint: '导入世界蓝图', exportBlueprint: '导出世界蓝图', importRun: '导入演算存档', exportRun: '导出演算存档', blueprintArchiveHint: '仅接受当前格式的冻结世界蓝图归档，并验证证书、来源快照和内容摘要。', runArchiveHint: '演算存档包含逻辑快照、事件、检查点和保留的世界蓝图，不包含本地缓存数据库。',
  overview: '世界首页', canon: '创作设定', map: '世界地图', build: '构建验证', simulation: '实时演算', textPlay: '故事舞台', back: '回到我的世界',
  status: '状态', documents: '文档', size: '大小', updated: '更新于', health: '健康度', projectPath: '项目路径', openFolder: '打开目录', chatWithAuthor: '与世界线助手对话',
  files: '文件', createFile: '新建文档', createFolder: '新建文件夹', path: '路径', save: '保存', saved: '已保存', saving: '保存中', dirty: '未保存', conflict: '版本冲突',
  edit: '编辑', object: '专用视图', preview: '预览', split: '分栏', history: '历史', backlinks: '反向链接', deleteEntry: '删除条目', renameMove: '移动/重命名', duplicateEntry: '复制条目',
  kind: '对象类型', revision: '修订', kindCharter: '世界宪章', kindCharacter: '角色', kindPlace: '地点', kindOrganization: '组织', kindSpecies: '物种', kindItem: '物品', kindConcept: '概念', kindRule: '规则', kindRelation: '关系', kindFact: '事实', kindTimeline: '时间线事件', kindScenario: '剧本', kindAsset: '资源', kindCustom: '自定义对象',
  canonIdentity: '身份与范围', canonFacets: '结构属性', canonReferences: '对象引用', canonSource: '权威真源', canonRuntime: '运行映射', canonRuntimeHint: '内部世界模型投影', canonSections: '章节', canonStatus: '正典状态', canonNoSummary: '这份对象还没有摘要；在一级标题后补充一段自然语言说明。', canonNoSections: '等待进一步构筑', canonNoSectionsHint: '使用二级标题组织身份、事实、关系、生命周期、行为、资源或来源，专用视图会自动形成对象档案。', canonNoFacets: '尚无结构属性；自然语言正文仍然是权威真源。', canonNoReferences: '正文中尚未发现稳定 ID 或 [[对象]] 引用。', canonSourceHint: '此视图只投影当前 Markdown，不创建第二份对象数据。',
  searchInProject: '搜索设定内容…', restoreServer: '载入磁盘版本', overwrite: '以当前内容重试', autosave: '自动保存已启用', externalChange: '检测到磁盘上的外部修改', openDocuments: '已打开文档',
  cut: '剪切', paste: '粘贴', pasteSamePath: '不能粘贴到原路径，请先选择目标文件夹。', trashConfirm: '该条目将移入可恢复的回收站。', importFiles: '导入文件', importingFiles: '正在流式导入',
  mapEmpty: '当前文档没有可解析的 worldline-map JSON 代码块。', mapHint: '地图编辑器只修改当前文档中的结构化地图块。', autoLayout: '自动布局', undo: '撤销', redo: '重做', validate: '验证', addNode: '添加节点', addEdge: '添加边', layers: '图层', visibility: '可见性', lock: '锁定', layerLocked: '该图层已锁定，节点不可编辑。', background: '底图资源', zoom: '缩放', visibleNodes: '视口节点', clusteredNodes: '个聚合节点',
  compile: '编译预览', freeze: '冻结并激活', sourceCoverage: '来源覆盖率', diagnostics: '诊断', questions: '创作问题', proposals: '提案审查', certificate: '闭包证书', answer: '回答', approve: '批准', reject: '拒绝', explain: '解释来源',
  noBuild: '尚未编译。编译会从当前稳定快照生成可审查的世界蓝图。', freezeReady: '所有闭包门禁已通过，可以冻结。', freezeBlocked: '仍有阻断项，不能冻结。',
  runs: '世界演算', newRun: '开始新演算', seed: '命运种子', startPaused: '创建后先暂停', pause: '暂停时间', resume: '继续流动', advance: '推进时间', autoAdvance: '自动演算与角色行动', stop: '结束演算', checkpoint: '保存此刻', checkpoints: '时光存档与分支', branch: '开启新世界线', replayBranch: '从这里开启分支', causalExplanation: '为什么会发生',
  logicalTime: '逻辑时间', sequence: '序列', queue: '未来队列', processes: '进程', reservations: '预留', fairness: '公平干预', deadlocks: '死锁恢复', livelocks: '活锁恢复', events: '事件流', entities: '实体', controls: '控制模式',
  interventions: '受控干预', legalInterventionHint: '只允许当前演算引擎给出的合法动作', selectActorFirst: '请先选择一个角色。', noLegalInterventions: '当前角色没有合法干预；可能已有活动进程或前置条件未满足。', action: '动作', duration: '时长', targets: '目标', costs: '代价', risks: '风险', applyIntervention: '执行干预', systems: '系统调度', actions: '动作定义', invariants: '不变量', nextWake: '下次唤醒', interval: '间隔', effects: '效果', preconditions: '前置条件', observations: '角色观察', limitedPerspective: '由世界事件派生的有限视角事实', noObservations: '尚无角色观察。', longestWait: '最长等待', noProgress: '无进展步数', healthy: '正常', writeAheadLog: '数据库预写日志', writer: '独占写入线程',
  runtimeMap: '运行地图', remaining: '剩余时间', mapProjectionClipped: '当前投影已按节点上限裁剪；缩小视口可查看更精确的区域。',
  ai: 'AI', aiEnabled: 'AI 已启用', aiDisabled: '仅确定性运行', modelCatalog: '模型目录', modelRoute: '模型路由', defaultReasoning: '默认推理强度', budget: '预算', budgetAvailable: '预算可用', budgetBlocked: '预算已阻断 AI', saveBudget: '保存预算', deterministicBudget: '明确设为零预算', context: '上下文包', decide: '让角色决策',
  actor: '角色', narrator: '叙事者', narrate: '叙述当前场景', choices: '合法选择', freeInput: '用自然语言描述意图…', submit: '提交', savePoint: '保存点', rephrase: '重新表述', retryChoice: '从保存点重试',
  storyStage: '视觉故事舞台', unavailable: '暂未接入演出器', templateNarration: '使用本地模板叙事', error: '操作失败', close: '关闭', confirm: '确认',
  localPromise: '离线优先 · 文件是真源 · 随时可迁移', beginJourney: '开始创作旅程', libraryGreeting: '把灵感写成真正会呼吸的世界', libraryLead: '在这里整理原创角色与设定，验证世界规则，然后亲自走进故事。', quickStart: '创作起点', recentWorlds: '最近的世界', worldCount: '个世界', workflow: '创作旅程', workflowHint: '每一步都建立在同一份世界真源上', emptyInspiration: '写下角色的名字，故事就会从这里醒来。', projectHome: '世界档案', projectHomeHint: '继续书写设定，或让这个世界开始自行运转。', canonCount: '正典对象', executableCount: '可运行规则', closureState: '构建状态', ready: '可以冻结', blocked: '仍需完善', payload: '结构化内容', evidence: '验证依据', canonProvenance: '正典与来源', sourceAnchors: '个来源锚点', runtimeConsole: '世界运行室', allStreams: '全部记录', callCount: '调用次数', inputTokens: '输入字数', outputTokens: '输出字数', estimatedCost: '预估费用', camera: '叙事镜头', run: '演算档案', place: '所在地点', presentActors: '在场角色', waitingNarration: '世界安静地等待着你的第一句旁白。', streaming: '正在书写', eventCount: '世界事件', observationCount: '角色观察', advancedData: '展开技术细节', mapNoProjection: '尚无可显示的运行地图', mapName: '名称', mapKind: '层级类型', mapParent: '上级区域', mapCapacity: '容纳数量', mapEntries: '入口节点', mapPermissions: '通行权限', mapHazards: '危险因素', edgeFrom: '起点', edgeTo: '终点', edgeBidirectional: '允许双向通行', edgeDistance: '距离', edgeDuration: '基础耗时', edgeModes: '交通方式', dynamicCondition: '动态通行条件', validationPassed: '地图验证通过',
  relocate: '迁移项目库', dryRun: '先检查', applyRelocation: '执行迁移', conflicts: '冲突', requiredSpace: '所需空间',
} as const

/** Describes the worldline locale key value exchanged across the package boundary.
 */
export type WorldlineLocaleKey = keyof typeof zh

declare module '@deepseek-ai/dsh-client-ui-slots' {
  interface LocaleNamespaceMap { worldlineStudio: WorldlineLocaleKey }
}

/** Identifies the package-owned en value.
 */
export const en = {
  nav: 'Worldline', title: 'Worldline Studio', subtitle: 'Compile lore into a verifiable, replayable, playable world.',
  local: 'Local only', chooseRoot: 'Choose a home for your stories', chooseRootHint: 'Choose a local folder for worlds, characters, and simulations. Every creative file remains yours.',
  chooseDirectory: 'Choose directory', retry: 'Retry', loading: 'Reading the Worldline project library…', rootError: 'Could not read the project library',
  library: 'Library', search: 'Search projects, tags, or descriptions…', newProject: 'New world', rescan: 'Rescan', rootSettings: 'Library settings',
  noProjects: 'No Worldline projects yet', noProjectsHint: 'Start from a structured template, or import an existing .worldline.zip world package.',
  create: 'Create', cancel: 'Cancel', projectName: 'Project name', description: 'Description', template: 'Template', tags: 'Tags',
  open: 'Open', copy: 'Create copy', copyProjectTitle: 'Create project copy', trash: 'Move to trash', trashShort: 'Trash', trashProjectTitle: 'Confirm move to trash', trashProjectHint: 'The complete project will move to recoverable trash and will not be permanently deleted now.', restore: 'Restore', trashBin: 'Trash', emptyTrash: 'Empty trash', emptyTrashTitle: 'Confirm empty trash', emptyTrashHint: 'Every world project and file in the trash will be permanently deleted. This action cannot be undone or recovered.', trashEmpty: 'The trash is empty', emptyTrashDone: 'Trash emptied',
  importProject: 'Import', exportProject: 'Export', sourcePath: 'Archive file', destinationPath: 'Save location', chooseArchive: 'Choose archive file', chooseSavePath: 'Choose save location', chooseProjectArchive: 'Choose world package', chooseBlueprintArchive: 'Choose blueprint archive', chooseRunArchive: 'Choose run archive', includeRuns: 'Include runs', importConflict: 'If project exists', importAsCopy: 'Create independent copy', replaceRecoverably: 'Replace and keep in trash', cancelOnConflict: 'Cancel import',
  importBlueprint: 'Import Blueprint', exportBlueprint: 'Export Blueprint', importRun: 'Import Run archive', exportRun: 'Export Run archive', blueprintArchiveHint: 'Only the current frozen Blueprint format is accepted; certificate, source snapshot, and content digests are verified.', runArchiveHint: 'Run archives contain logical snapshots, events, checkpoints, and the retained Blueprint—not a SQLite cache database.',
  overview: 'Overview', canon: 'Canon', map: 'Map', build: 'Build', simulation: 'Simulation', textPlay: 'Text play', back: 'Back to library',
  status: 'Status', documents: 'Documents', size: 'Size', updated: 'Updated', health: 'Health', projectPath: 'Project path', openFolder: 'Open folder', chatWithAuthor: 'Chat with Worldline Author',
  files: 'Files', createFile: 'New document', createFolder: 'New folder', path: 'Path', save: 'Save', saved: 'Saved', saving: 'Saving', dirty: 'Unsaved', conflict: 'Revision conflict',
  edit: 'Edit', object: 'Object view', preview: 'Preview', split: 'Split', history: 'History', backlinks: 'Backlinks', deleteEntry: 'Delete entry', renameMove: 'Move / rename', duplicateEntry: 'Duplicate entry',
  kind: 'Object kind', revision: 'Revision', kindCharter: 'World charter', kindCharacter: 'Character', kindPlace: 'Place', kindOrganization: 'Organization', kindSpecies: 'Species', kindItem: 'Item', kindConcept: 'Concept', kindRule: 'Rule', kindRelation: 'Relationship', kindFact: 'Fact', kindTimeline: 'Timeline event', kindScenario: 'Scenario', kindAsset: 'Asset', kindCustom: 'Custom object',
  canonIdentity: 'Identity and scope', canonFacets: 'Structured facets', canonReferences: 'Object references', canonSource: 'Source of truth', canonRuntime: 'Runtime mapping', canonRuntimeHint: 'Internal world-model projection', canonSections: 'Sections', canonStatus: 'Canon status', canonNoSummary: 'This object has no summary yet; add a natural-language paragraph after its top-level heading.', canonNoSections: 'Ready for deeper worldbuilding', canonNoSectionsHint: 'Use level-two headings for identity, facts, relationships, lifecycle, behavior, assets, or provenance; this view will shape them into an object dossier.', canonNoFacets: 'No structured facets yet; the natural-language document remains authoritative.', canonNoReferences: 'No stable IDs or [[object]] references were found in the document.', canonSourceHint: 'This view projects the current Markdown and never creates a second object database.',
  searchInProject: 'Search canon…', restoreServer: 'Load disk version', overwrite: 'Retry with current content', autosave: 'Autosave enabled', externalChange: 'An external disk change was detected', openDocuments: 'Open documents',
  cut: 'Cut', paste: 'Paste', pasteSamePath: 'Choose a destination folder before pasting into the same path.', trashConfirm: 'This entry will move to the recoverable trash.', importFiles: 'Import files', importingFiles: 'Streaming import',
  mapEmpty: 'The current document has no parseable worldline-map JSON fence.', mapHint: 'The map editor changes only the structured map block in the current document.', autoLayout: 'Auto layout', undo: 'Undo', redo: 'Redo', validate: 'Validate', addNode: 'Add node', addEdge: 'Add edge', layers: 'Layers', visibility: 'Visibility', lock: 'Lock', layerLocked: 'This layer is locked; its nodes cannot be edited.', background: 'Background asset', zoom: 'Zoom', visibleNodes: 'viewport nodes', clusteredNodes: 'clustered nodes',
  compile: 'Compile preview', freeze: 'Freeze and activate', sourceCoverage: 'Source coverage', diagnostics: 'Diagnostics', questions: 'Creative questions', proposals: 'Proposal review', certificate: 'Closure certificate', answer: 'Answer', approve: 'Approve', reject: 'Reject', explain: 'Explain source',
  noBuild: 'Not compiled yet. Compile a stable source snapshot into a reviewable Blueprint.', freezeReady: 'All closure gates pass; this build can be frozen.', freezeBlocked: 'Blocking items remain; this build cannot be frozen.',
  runs: 'Runs', newRun: 'New run', seed: 'Random seed', startPaused: 'Start paused', pause: 'Pause', resume: 'Resume', advance: 'Advance', autoAdvance: 'Auto-run and actor actions', stop: 'Stop', checkpoint: 'Checkpoint', checkpoints: 'Checkpoints and replay', branch: 'Create branch', replayBranch: 'Replay as branch', causalExplanation: 'Causal explanation',
  logicalTime: 'Logical time', sequence: 'Sequence', queue: 'Future queue', processes: 'Processes', reservations: 'Reservations', fairness: 'Fairness interventions', deadlocks: 'Deadlock recovery', livelocks: 'Livelock recovery', events: 'Event stream', entities: 'Entities', controls: 'Control mode',
  interventions: 'Controlled interventions', legalInterventionHint: 'Only actions currently projected as legal by Runtime', selectActorFirst: 'Select an actor first.', noLegalInterventions: 'This actor has no legal intervention now; an active process or unmet precondition may block it.', action: 'Action', duration: 'Duration', targets: 'Targets', costs: 'Costs', risks: 'Risks', applyIntervention: 'Apply intervention', systems: 'System schedule', actions: 'Action definitions', invariants: 'Invariants', nextWake: 'Next wake', interval: 'Interval', effects: 'Effects', preconditions: 'Preconditions', observations: 'Actor observations', limitedPerspective: 'Limited-perspective facts derived from world events', noObservations: 'No actor observations yet.', longestWait: 'Longest wait', noProgress: 'No-progress steps', healthy: 'Healthy', writeAheadLog: 'Database write-ahead log', writer: 'Exclusive writer thread',
  runtimeMap: 'Runtime map', remaining: 'remaining', mapProjectionClipped: 'This projection reached its node limit; narrow the viewport for a more precise area.',
  ai: 'AI', aiEnabled: 'AI enabled', aiDisabled: 'Deterministic only', modelCatalog: 'Model catalog', modelRoute: 'Model route', defaultReasoning: 'Default reasoning', budget: 'Budget', budgetAvailable: 'Budget available', budgetBlocked: 'Budget blocks AI', saveBudget: 'Save budget', deterministicBudget: 'Explicit zero budget', context: 'Context pack', decide: 'Let actor decide',
  actor: 'Actor', narrator: 'Narrator', narrate: 'Narrate current scene', choices: 'Legal choices', freeInput: 'Describe an intent in natural language…', submit: 'Submit', savePoint: 'Save point', rephrase: 'Rephrase', retryChoice: 'Retry from save',
  storyStage: 'StoryStage', unavailable: 'Unavailable', templateNarration: 'Template narration', error: 'Operation failed', close: 'Close', confirm: 'Confirm',
  localPromise: 'Offline-first · Files are truth · Move anytime', beginJourney: 'Begin your journey', libraryGreeting: 'Turn inspiration into a world that breathes', libraryLead: 'Shape original characters and lore, validate world rules, then step into the story.', quickStart: 'Creative starting points', recentWorlds: 'Recent worlds', worldCount: 'worlds', workflow: 'Creative journey', workflowHint: 'Every step shares one source of truth', emptyInspiration: 'Write a character name and the story will wake from here.', projectHome: 'World dossier', projectHomeHint: 'Continue the lore, or let this world begin to move on its own.', canonCount: 'Canon objects', executableCount: 'Executable rules', closureState: 'Build state', ready: 'Ready to freeze', blocked: 'Needs work', payload: 'Structured content', evidence: 'Evidence', canonProvenance: 'Canon and provenance', sourceAnchors: 'source anchors', runtimeConsole: 'World runtime room', allStreams: 'All records', callCount: 'Calls', inputTokens: 'Input tokens', outputTokens: 'Output tokens', estimatedCost: 'Estimated cost', camera: 'Camera', run: 'Run', place: 'Place', presentActors: 'Present actors', waitingNarration: 'The world is quietly waiting for its first line of narration.', streaming: 'Writing', eventCount: 'world events', observationCount: 'actor observations', advancedData: 'Technical details', mapNoProjection: 'No runtime map is available yet', mapName: 'Name', mapKind: 'Level kind', mapParent: 'Parent area', mapCapacity: 'Capacity', mapEntries: 'Entry nodes', mapPermissions: 'Permissions', mapHazards: 'Hazards', edgeFrom: 'From', edgeTo: 'To', edgeBidirectional: 'Bidirectional travel', edgeDistance: 'Distance', edgeDuration: 'Base duration', edgeModes: 'Travel modes', dynamicCondition: 'Dynamic condition', validationPassed: 'Map validation passed',
  relocate: 'Relocate library', dryRun: 'Check first', applyRelocation: 'Relocate', conflicts: 'Conflicts', requiredSpace: 'Required space',
} satisfies Record<WorldlineLocaleKey, string>
